spring:
  application:
    name: todo-core
  profiles:
    active: dev
server:
  port: 8095
  servlet:
    context-path: /todo
  error:
    include-message: always
logging:
  level:
    org.springframework.security: TRACE

